version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: centific-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/local.db:/app/local.db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: centific-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
