-- =============================================================================
--  Centific Pricing Intelligence â€” PostgreSQL Schema (DDL)
--  Target:  PostgreSQL 14+
--  Purpose: Back the Centific Pricing Intelligence frontend
-- =============================================================================

DROP TABLE IF EXISTS accuracy_buckets      CASCADE;
DROP TABLE IF EXISTS top_deal_today        CASCADE;
DROP TABLE IF EXISTS activity_snapshot     CASCADE;
DROP TABLE IF EXISTS win_rate_insights     CASCADE;
DROP TABLE IF EXISTS win_rate_points       CASCADE;
DROP TABLE IF EXISTS pricing_settings      CASCADE;
DROP TABLE IF EXISTS approvals             CASCADE;
DROP TABLE IF EXISTS contract_risks        CASCADE;
DROP TABLE IF EXISTS benchmarks            CASCADE;
DROP TABLE IF EXISTS rfp_hil_progress      CASCADE;
DROP TABLE IF EXISTS hil_checkpoints       CASCADE;
DROP TABLE IF EXISTS pricing_scenarios     CASCADE;
DROP TABLE IF EXISTS rfps                  CASCADE;
DROP TABLE IF EXISTS clients               CASCADE;

-- -----------------------------------------------------------------------------
--  1. clients
-- -----------------------------------------------------------------------------
CREATE TABLE clients (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT    NOT NULL UNIQUE
);

-- -----------------------------------------------------------------------------
--  2. rfps  (central table)
-- -----------------------------------------------------------------------------
CREATE TABLE rfps (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rfp_code                TEXT        NOT NULL UNIQUE,
    name                    TEXT        NOT NULL,
    short_label             TEXT,
    client_id               INTEGER     NOT NULL REFERENCES clients(id) ON DELETE RESTRICT,
    category                TEXT        NOT NULL CHECK (category IN
                              ('Call Center','Translation','IT Services','BPO','Interpretation')),
    description             TEXT,
    tcv_base                BIGINT      NOT NULL,
    pricing_model           TEXT        NOT NULL,
    scenario_used           TEXT        CHECK (scenario_used IN ('Conservative','Base','Aggressive')),
    renewal_date            TEXT,
    submitted_date          TEXT,
    duration                TEXT,
    locale                  TEXT,
    win_probability         INTEGER     CHECK (win_probability BETWEEN 0 AND 100),
    risk_level              TEXT        CHECK (risk_level IN ('Low','Medium','High')),
    hil_stage               TEXT,
    status                  TEXT        NOT NULL CHECK (status IN
                              ('Active','Priced','Awarded','Won','Lost','Archived')),
    pipeline_stage          TEXT        CHECK (pipeline_stage IN
                              ('Ingesting','Extracting','Pricing','HIL Review','Approved')),
    current_hil_level       INTEGER     CHECK (current_hil_level BETWEEN 0 AND 5),
    scenario_assumptions    TEXT,
    benchmark_scope         TEXT,
    benchmark_note          TEXT,
    tcv_display             TEXT,
    active_in_pipeline      BOOLEAN     NOT NULL DEFAULT FALSE,
    active_pipeline_rank    INTEGER,
    is_current              BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_rfps_client         ON rfps(client_id);
CREATE INDEX idx_rfps_status         ON rfps(status);
CREATE INDEX idx_rfps_category       ON rfps(category);
CREATE INDEX idx_rfps_pricing_model  ON rfps(pricing_model);
CREATE INDEX idx_rfps_pipeline_stage ON rfps(pipeline_stage);

-- -----------------------------------------------------------------------------
--  3. pricing_scenarios
-- -----------------------------------------------------------------------------
CREATE TABLE pricing_scenarios (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rfp_id                INTEGER NOT NULL REFERENCES rfps(id) ON DELETE CASCADE,
    scenario_type         TEXT    NOT NULL CHECK (scenario_type IN ('Conservative','Base','Aggressive')),
    annual_value_display  TEXT    NOT NULL,
    period_sub            TEXT    NOT NULL,
    volume_display        TEXT    NOT NULL,
    volume_factor         TEXT    NOT NULL,
    margin_pct            TEXT    NOT NULL,
    sell_rate_display     TEXT    NOT NULL,
    is_recommended        BOOLEAN NOT NULL DEFAULT FALSE,
    UNIQUE (rfp_id, scenario_type)
);

-- -----------------------------------------------------------------------------
--  4. hil_checkpoints (master: 5 fixed levels)
-- -----------------------------------------------------------------------------
CREATE TABLE hil_checkpoints (
    level       INTEGER PRIMARY KEY CHECK (level BETWEEN 1 AND 5),
    title       TEXT NOT NULL,
    description TEXT NOT NULL,
    owner_role  TEXT NOT NULL
);

-- -----------------------------------------------------------------------------
--  5. rfp_hil_progress
-- -----------------------------------------------------------------------------
CREATE TABLE rfp_hil_progress (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rfp_id     INTEGER NOT NULL REFERENCES rfps(id) ON DELETE CASCADE,
    level      INTEGER NOT NULL REFERENCES hil_checkpoints(level),
    status     TEXT    NOT NULL CHECK (status IN ('done','pending','waiting')),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (rfp_id, level)
);

-- -----------------------------------------------------------------------------
--  6. benchmarks
-- -----------------------------------------------------------------------------
CREATE TABLE benchmarks (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rfp_id        INTEGER NOT NULL REFERENCES rfps(id) ON DELETE CASCADE,
    label         TEXT    NOT NULL,
    rate_display  TEXT    NOT NULL,
    bar_width_pct INTEGER NOT NULL CHECK (bar_width_pct BETWEEN 0 AND 100),
    color_css     TEXT    NOT NULL,
    sort_order    INTEGER NOT NULL
);

-- -----------------------------------------------------------------------------
--  7. contract_risks
-- -----------------------------------------------------------------------------
CREATE TABLE contract_risks (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rfp_id      INTEGER NOT NULL REFERENCES rfps(id) ON DELETE CASCADE,
    severity    TEXT    NOT NULL CHECK (severity IN ('low','med','high')),
    description TEXT    NOT NULL,
    sort_order  INTEGER NOT NULL DEFAULT 0
);

-- -----------------------------------------------------------------------------
--  8. approvals
-- -----------------------------------------------------------------------------
CREATE TABLE approvals (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rfp_id      INTEGER NOT NULL REFERENCES rfps(id) ON DELETE CASCADE,
    level       INTEGER NOT NULL REFERENCES hil_checkpoints(level),
    title       TEXT    NOT NULL,
    meta        TEXT,
    status      TEXT    NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending','approved','rejected')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    actioned_at TIMESTAMPTZ
);
CREATE INDEX idx_approvals_status ON approvals(status);

-- -----------------------------------------------------------------------------
--  9. pricing_settings
-- -----------------------------------------------------------------------------
CREATE TABLE pricing_settings (
    key         TEXT    PRIMARY KEY,
    value       TEXT    NOT NULL,
    label       TEXT    NOT NULL,
    description TEXT    NOT NULL,
    kind        TEXT    NOT NULL CHECK (kind IN ('input','toggle','input_wide')),
    sort_order  INTEGER NOT NULL
);

-- -----------------------------------------------------------------------------
-- 10. win_rate_points
-- -----------------------------------------------------------------------------
CREATE TABLE win_rate_points (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    range_type   TEXT    NOT NULL CHECK (range_type IN ('week','month','quarter')),
    period_label TEXT    NOT NULL,
    win_rate_pct INTEGER NOT NULL CHECK (win_rate_pct BETWEEN 0 AND 100),
    seq          INTEGER NOT NULL,
    UNIQUE (range_type, seq)
);

-- -----------------------------------------------------------------------------
-- 11. win_rate_insights
-- -----------------------------------------------------------------------------
CREATE TABLE win_rate_insights (
    range_type   TEXT    NOT NULL CHECK (range_type IN ('week','month','quarter')),
    slot         INTEGER NOT NULL CHECK (slot BETWEEN 1 AND 3),
    label        TEXT    NOT NULL,
    value        TEXT    NOT NULL,
    color_css    TEXT,
    header_label TEXT    NOT NULL,
    sub_label    TEXT    NOT NULL,
    PRIMARY KEY (range_type, slot)
);

-- -----------------------------------------------------------------------------
-- 12. activity_snapshot
-- -----------------------------------------------------------------------------
CREATE TABLE activity_snapshot (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    variant    TEXT    NOT NULL UNIQUE
                 CHECK (variant IN ('upload','tools','approvals','time')),
    icon       TEXT    NOT NULL,
    value      TEXT    NOT NULL,
    label      TEXT    NOT NULL,
    trend_dir  TEXT    NOT NULL CHECK (trend_dir IN ('up','down','flat')),
    trend_text TEXT    NOT NULL,
    sort_order INTEGER NOT NULL
);

-- -----------------------------------------------------------------------------
-- 13. top_deal_today (single-row table)
-- -----------------------------------------------------------------------------
CREATE TABLE top_deal_today (
    id      INTEGER PRIMARY KEY CHECK (id = 1),
    summary TEXT    NOT NULL
);

-- -----------------------------------------------------------------------------
-- 14. accuracy_buckets
-- -----------------------------------------------------------------------------
CREATE TABLE accuracy_buckets (
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bucket_label   TEXT    NOT NULL UNIQUE,
    deal_count     INTEGER NOT NULL,
    in_sweet_spot  BOOLEAN NOT NULL DEFAULT FALSE,
    seq            INTEGER NOT NULL
);
